condition:
  method: dps
  params:
    step_size: 0.0001
  cond_step_schedule:
    name: subiter
    subiter: 1

diffusion:
  schedule_sampler: uniform
  clip_denoised: True
  target: diffusion.gaussian_diffusion_alone.ConditionalDiffusion
  params:
    timesteps: 1000
    sampling_timesteps: 1000
    objective: pred_v
    beta_schedule: linear
    clip_x0: [-1., 1.]

recon:
  imgsize: [128, 128]
  voxsize: [1.65, 1.65]

model:
  target: diffusion.unet.unet_learn_emb.UNetModelWrapper
  params:
    dim: 
    - 1
    - 128
    - 128
    num_channels: 64
    num_cond_channels: 0
    attention_resolutions: 
    - 8
    num_res_blocks: 2
    channel_mult:
    - 1
    - 1
    - 2
    - 3
    - 4
    num_head_channels: 64
    num_heads: 4
    use_scale_shift_norm: True
    use_mid_attn: True

ckpt_path: /path/to/your/checkpoint/ckpt_50000.pt

phantom: ./phantom/bern/345_027.npz
system_matrix: ./misc/G_nontof_nx-2d_481x480_128x128_1.65mm.npz
ipsf_model: ./misc/ipsf_nontof_nx-2d.npz
count: 0.4

save_steps: 0

